{{- if .Values.ingress.enabled -}}
{{- $fullName := include "version-monitor.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "version-monitor.name" . }}
    helm.sh/chart: {{ include "version-monitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
  {{- end }}
